name: "Example MCP Server"

services:
  server_mcp:
    container_name: example_mcp_server
    build:
      context: .
      dockerfile: dockerfile
    restart: unless-stopped
    ports:
      - 8000:8000