name: "Example MCP Server"

services:
  server-mcp:
    container_name: example-mcp-server
    build:
      context: .
      dockerfile: dockerfile
      tags:
        - example-mcp-server
    restart: unless-stopped
    ports:
      - 8000:8000